server:
  port: 8083

keycloak:
  auth-server-url: http://94.198.218.71:8080/
  realm: individualsAPI
  admin-username: admin
  admin-password: admin
  registration-uri: ${keycloak.auth-server-url}/admin/realms/individualsAPI/users

person-service:
  base-url: http://localhost:8084/v1/api/users/
  registration-url: http://localhost:8084/v1/api/registration/


spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
            user-name-attribute: preferred_username
            jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
            authorization-uri: ${keycloak.auth-server-url}/realms/individualsAPI/protocol/openid-connect/token
        registration:
          keycloak:
            client-id: individualsAPI
            client-secret: OPBa0h19GP0QLGMYwj8Cu3PHHalg5YJx
            authorization-grant-type: client_credentials

logging:
  level:
    reactor.netty.http.client: DEBUG