server:
  port: 8083

keycloak:
  auth-server-url: http://localhost:8180
  realm: individualsAPI
  admin-username: admin
  admin-password: admin

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
            user-name-attribute: preferred_username
            jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
            authorization-uri: ${keycloak.auth-server-url}/realms/individualsAPI/protocol/openid-connect/token
            registration-uri: ${keycloak.auth-server-url}/admin/realms/individualsAPI/users
        registration:
          keycloak:
            client-id: individualsAPI
            client-secret: Xn4kGk3lEnxCiB0Garvm4vk9L48DWi9e
            authorization-grant-type: client_credentials

logging:
  level:
    reactor.netty.http.client: DEBUG